import { MigrationInterface, QueryRunner } from "typeorm";

export class SystemTimePersistence1781409224593 implements MigrationInterface {
    name = 'SystemTimePersistence1781409224593'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "password_reset_token" DROP CONSTRAINT "FK_password_reset_token_user"`);
        await queryRunner.query(`ALTER TABLE "transfer_person" DROP CONSTRAINT "fk_transfer_person_transfer"`);
        await queryRunner.query(`ALTER TABLE "transfer_person" DROP CONSTRAINT "fk_transfer_person_person"`);
        await queryRunner.query(`ALTER TABLE "user_role_history" DROP CONSTRAINT "fk_historial_rol_usuario"`);
        await queryRunner.query(`ALTER TABLE "user_role_history" DROP CONSTRAINT "fk_historial_rol_cambiado_por"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP CONSTRAINT "fk_transfer_history_user"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP CONSTRAINT "fk_transfer_history_transfer"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "fk_transfer_request"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "fk_session_camp"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "fk_sesion_usuario"`);
        await queryRunner.query(`ALTER TABLE "person_status_history" DROP CONSTRAINT "fk_person_history"`);
        await queryRunner.query(`ALTER TABLE "person_status_history" DROP CONSTRAINT "fk_historial_cambiado_por"`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" DROP CONSTRAINT "fk_request_person_request"`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" DROP CONSTRAINT "fk_request_person_person"`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" DROP CONSTRAINT "fk_request_person_occupation"`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" DROP CONSTRAINT "fk_sol_rec_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" DROP CONSTRAINT "fk_sol_rec_solicitud"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "fk_notification_camp"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "fk_notificacion_usuario"`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" DROP CONSTRAINT "fk_alerta_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" DROP CONSTRAINT "fk_alerta_movimiento"`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" DROP CONSTRAINT "fk_alert_camp"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP CONSTRAINT "fk_movimiento_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP CONSTRAINT "fk_movimiento_registrado_por"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP CONSTRAINT "fk_movimiento_camp"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "fk_sic_respondido_por"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "fk_sic_creado_por"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "fk_icr_origin_camp"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "fk_icr_destination_camp"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" DROP CONSTRAINT "fk_exp_consumed_expedition"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" DROP CONSTRAINT "fk_exp_cons_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" DROP CONSTRAINT "fk_exp_cons_registrado_por"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" DROP CONSTRAINT "fk_exp_cons_movimiento"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" DROP CONSTRAINT "fk_exp_obten_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" DROP CONSTRAINT "fk_exp_obten_registrado_por"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" DROP CONSTRAINT "fk_exp_obten_movimiento"`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" DROP CONSTRAINT "fk_exp_obtained_expedition"`);
        await queryRunner.query(`ALTER TABLE "expedition_participant" DROP CONSTRAINT "fk_exp_participant_person"`);
        await queryRunner.query(`ALTER TABLE "expedition_participant" DROP CONSTRAINT "fk_exp_participant_expedition"`);
        await queryRunner.query(`ALTER TABLE "expedition" DROP CONSTRAINT "fk_expedition_camp"`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" DROP CONSTRAINT "fk_transfer_resource_type"`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" DROP CONSTRAINT "fk_transfer_resource_transfer"`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" DROP CONSTRAINT "fk_transfer_resource_recorded_by"`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" DROP CONSTRAINT "fk_transfer_resource_movement"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" DROP CONSTRAINT "fk_recoleccion_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" DROP CONSTRAINT "fk_recoleccion_registrado_por"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" DROP CONSTRAINT "fk_recoleccion_movimiento"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" DROP CONSTRAINT "fk_collection_person"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" DROP CONSTRAINT "fk_collection_camp"`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" DROP CONSTRAINT "fk_camplogro_logro"`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" DROP CONSTRAINT "fk_camplogro_desbloqueado_por"`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" DROP CONSTRAINT "fk_camp_achievement_camp"`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" DROP CONSTRAINT "fk_inventory_camp"`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" DROP CONSTRAINT "fk_inventario_tipo_recurso"`);
        await queryRunner.query(`ALTER TABLE "ai_admission_report" DROP CONSTRAINT "fk_reporte_solicitud"`);
        await queryRunner.query(`ALTER TABLE "access_log" DROP CONSTRAINT "fk_log_sesion"`);
        await queryRunner.query(`ALTER TABLE "access_log" DROP CONSTRAINT "fk_access_log_user"`);
        await queryRunner.query(`ALTER TABLE "access_log" DROP CONSTRAINT "fk_access_log_camp"`);
        await queryRunner.query(`ALTER TABLE "person" DROP CONSTRAINT "person_character_check"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "chk_intercamp_planned_dates_required_when_approved"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "chk_intercamp_arrival_after_departure_by_minute"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP CONSTRAINT "chk_intercamp_response_fields_populated"`);
        await queryRunner.query(`CREATE TABLE "system_time" ("id" integer NOT NULL DEFAULT '1', "offset_milliseconds" bigint NOT NULL DEFAULT '0', "last_server_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_147ff03c766b70716c10a700ba4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP COLUMN "previous_status"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD "previous_status" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP COLUMN "new_status"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD "new_status" text NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_transfer_status"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "chk_transfer_status_values"`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD "status" text NOT NULL DEFAULT 'PENDING_DEPARTURE'`);
        await queryRunner.query(`ALTER TABLE "transfer" ALTER COLUMN "rations_for_trip" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "uq_sesion_token"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "token" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "UQ_232f8e85d7633bd6ddfad421696" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum" RENAME TO "session_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" TYPE "public"."session_status_enum" USING "status"::"text"::"public"."session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "daily_amount_produced" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "daily_ration_consumed" SET DEFAULT '1.00'`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "critical_threshold_percent" SET DEFAULT '50.00'`);
        await queryRunner.query(`ALTER TYPE "public"."intercamp_request_status_enum" RENAME TO "intercamp_request_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."intercamp_request_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELED')`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" TYPE "public"."intercamp_request_status_enum" USING "status"::"text"::"public"."intercamp_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."intercamp_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "planned_departure_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "planned_arrival_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "person_requirements" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "email_outbox" ALTER COLUMN "payload" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TYPE "public"."expedition_status_enum" RENAME TO "expedition_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."expedition_status_enum" AS ENUM('PLANNED', 'IN_PROGRESS', 'DELAYED', 'COMPLETED', 'LOST', 'RETURNED_AFTER_LOST', 'CANCELED')`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" TYPE "public"."expedition_status_enum" USING "status"::"text"::"public"."expedition_status_enum"`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" SET DEFAULT 'PLANNED'`);
        await queryRunner.query(`DROP TYPE "public"."expedition_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ALTER COLUMN "expected_amount" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ALTER COLUMN "actual_amount" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" ALTER COLUMN "is_seen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ALTER COLUMN "current_amount" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ALTER COLUMN "minimum_alert_amount" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TYPE "public"."camp_status_enum" RENAME TO "camp_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."camp_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'ABANDONED')`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" TYPE "public"."camp_status_enum" USING "status"::"text"::"public"."camp_status_enum"`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."camp_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "minimum_daily_ration_per_person" SET DEFAULT '1.00'`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "stock_alert_threshold_percentage" SET DEFAULT '20.00'`);
        await queryRunner.query(`ALTER TYPE "public"."admission_request_status_enum" RENAME TO "admission_request_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."admission_request_status_enum" AS ENUM('PENDING_AI', 'PENDING_ADMIN', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" TYPE "public"."admission_request_status_enum" USING "status"::"text"::"public"."admission_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" SET DEFAULT 'PENDING_AI'`);
        await queryRunner.query(`DROP TYPE "public"."admission_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "metric_key" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "operator" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "target_value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "scope" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_transfer_status" ON "transfer" ("status") `);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD CONSTRAINT "chk_transfer_history_new_status_values" CHECK ("new_status" IN ('PENDING_DEPARTURE','COMPLETED','CANCELED'))`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD CONSTRAINT "chk_transfer_history_previous_status_values" CHECK ("previous_status" IN ('PENDING_DEPARTURE','COMPLETED','CANCELED'))`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "chk_transfer_status_values" CHECK ("status" IN ('PENDING_DEPARTURE','IN_TRANSIT','COMPLETED','CANCELED'))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transfer" DROP CONSTRAINT "chk_transfer_status_values"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP CONSTRAINT "chk_transfer_history_previous_status_values"`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP CONSTRAINT "chk_transfer_history_new_status_values"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transfer_status"`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "scope" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "target_value" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "operator" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievement" ALTER COLUMN "metric_key" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."admission_request_status_enum_old" AS ENUM('PENDING_AI', 'PENDING_ADMIN', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" TYPE "public"."admission_request_status_enum_old" USING "status"::"text"::"public"."admission_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "admission_request" ALTER COLUMN "status" SET DEFAULT 'PENDING_AI'`);
        await queryRunner.query(`DROP TYPE "public"."admission_request_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."admission_request_status_enum_old" RENAME TO "admission_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "stock_alert_threshold_percentage" SET DEFAULT 20.00`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "minimum_daily_ration_per_person" SET DEFAULT 1.00`);
        await queryRunner.query(`CREATE TYPE "public"."camp_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE', 'ABANDONED')`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" TYPE "public"."camp_status_enum_old" USING "status"::"text"::"public"."camp_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "camp" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."camp_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."camp_status_enum_old" RENAME TO "camp_status_enum"`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ALTER COLUMN "minimum_alert_amount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ALTER COLUMN "current_amount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" ALTER COLUMN "is_seen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ALTER COLUMN "actual_amount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ALTER COLUMN "expected_amount" SET DEFAULT 0.00`);
        await queryRunner.query(`CREATE TYPE "public"."expedition_status_enum_old" AS ENUM('PLANNED', 'COMPLETED', 'CANCELED', 'IN_PROGRESS', 'DELAYED', 'LOST', 'RETURNED_AFTER_LOST')`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" TYPE "public"."expedition_status_enum_old" USING "status"::"text"::"public"."expedition_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "expedition" ALTER COLUMN "status" SET DEFAULT 'PLANNED'`);
        await queryRunner.query(`DROP TYPE "public"."expedition_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."expedition_status_enum_old" RENAME TO "expedition_status_enum"`);
        await queryRunner.query(`ALTER TABLE "email_outbox" ALTER COLUMN "payload" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "person_requirements" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "planned_arrival_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "planned_departure_date" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."intercamp_request_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELED', 'DRAFT')`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" TYPE "public"."intercamp_request_status_enum_old" USING "status"::"text"::"public"."intercamp_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."intercamp_request_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."intercamp_request_status_enum_old" RENAME TO "intercamp_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "critical_threshold_percent" SET DEFAULT 50.00`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "daily_ration_consumed" SET DEFAULT 1.00`);
        await queryRunner.query(`ALTER TABLE "occupation" ALTER COLUMN "daily_amount_produced" SET DEFAULT 0.00`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum_old" AS ENUM('ACTIVE', 'EXPIRED', 'CLOSED')`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" TYPE "public"."session_status_enum_old" USING "status"::"text"::"public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum_old" RENAME TO "session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "UQ_232f8e85d7633bd6ddfad421696"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "token" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "uq_sesion_token" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "transfer" ALTER COLUMN "rations_for_trip" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "transfer" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_status_enum" AS ENUM('PENDING_DEPARTURE', 'COMPLETED', 'CANCELED', 'IN_TRANSIT')`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD "status" "public"."transfer_status_enum" NOT NULL DEFAULT 'PENDING_DEPARTURE'`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "chk_transfer_status_values" CHECK ((status = ANY (ARRAY['PENDING_DEPARTURE'::transfer_status_enum, 'IN_TRANSIT'::transfer_status_enum, 'COMPLETED'::transfer_status_enum, 'CANCELED'::transfer_status_enum])))`);
        await queryRunner.query(`CREATE INDEX "idx_transfer_status" ON "transfer" ("status") `);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP COLUMN "new_status"`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_status_enum" AS ENUM('PENDING_DEPARTURE', 'COMPLETED', 'CANCELED', 'IN_TRANSIT')`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD "new_status" "public"."transfer_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_history" DROP COLUMN "previous_status"`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_status_enum" AS ENUM('PENDING_DEPARTURE', 'COMPLETED', 'CANCELED', 'IN_TRANSIT')`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD "previous_status" "public"."transfer_status_enum" NOT NULL`);
        await queryRunner.query(`DROP TABLE "system_time"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "chk_intercamp_response_fields_populated" CHECK (((status = ANY (ARRAY['DRAFT'::intercamp_request_status_enum, 'PENDING'::intercamp_request_status_enum])) OR ((responded_by IS NOT NULL) AND (response_date IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "chk_intercamp_arrival_after_departure_by_minute" CHECK (((planned_departure_date IS NULL) OR (planned_arrival_date IS NULL) OR (planned_arrival_date > (planned_departure_date + '00:01:00'::interval))))`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "chk_intercamp_planned_dates_required_when_approved" CHECK (((status <> 'APPROVED'::intercamp_request_status_enum) OR ((planned_departure_date IS NOT NULL) AND (planned_arrival_date IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "person" ADD CONSTRAINT "person_character_check" CHECK (("character" = ANY (ARRAY[1, 2, 3])))`);
        await queryRunner.query(`ALTER TABLE "access_log" ADD CONSTRAINT "fk_access_log_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "access_log" ADD CONSTRAINT "fk_access_log_user" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "access_log" ADD CONSTRAINT "fk_log_sesion" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ai_admission_report" ADD CONSTRAINT "fk_reporte_solicitud" FOREIGN KEY ("request_id") REFERENCES "admission_request"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ADD CONSTRAINT "fk_inventario_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "camp_inventory" ADD CONSTRAINT "fk_inventory_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" ADD CONSTRAINT "fk_camp_achievement_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" ADD CONSTRAINT "fk_camplogro_desbloqueado_por" FOREIGN KEY ("unlocked_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "camp_achievement" ADD CONSTRAINT "fk_camplogro_logro" FOREIGN KEY ("logro_id") REFERENCES "achievement"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ADD CONSTRAINT "fk_collection_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ADD CONSTRAINT "fk_collection_person" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ADD CONSTRAINT "fk_recoleccion_movimiento" FOREIGN KEY ("movement_id") REFERENCES "inventory_movement"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ADD CONSTRAINT "fk_recoleccion_registrado_por" FOREIGN KEY ("recorded_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "daily_collection_record" ADD CONSTRAINT "fk_recoleccion_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" ADD CONSTRAINT "fk_transfer_resource_movement" FOREIGN KEY ("movement_id") REFERENCES "inventory_movement"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" ADD CONSTRAINT "fk_transfer_resource_recorded_by" FOREIGN KEY ("recorded_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" ADD CONSTRAINT "fk_transfer_resource_transfer" FOREIGN KEY ("transfer_id") REFERENCES "transfer"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "delivered_transfer_resource" ADD CONSTRAINT "fk_transfer_resource_type" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition" ADD CONSTRAINT "fk_expedition_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_participant" ADD CONSTRAINT "fk_exp_participant_expedition" FOREIGN KEY ("expedition_id") REFERENCES "expedition"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_participant" ADD CONSTRAINT "fk_exp_participant_person" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" ADD CONSTRAINT "fk_exp_obtained_expedition" FOREIGN KEY ("expedition_id") REFERENCES "expedition"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" ADD CONSTRAINT "fk_exp_obten_movimiento" FOREIGN KEY ("movement_id") REFERENCES "inventory_movement"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" ADD CONSTRAINT "fk_exp_obten_registrado_por" FOREIGN KEY ("recorded_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_obtained" ADD CONSTRAINT "fk_exp_obten_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" ADD CONSTRAINT "fk_exp_cons_movimiento" FOREIGN KEY ("movement_id") REFERENCES "inventory_movement"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" ADD CONSTRAINT "fk_exp_cons_registrado_por" FOREIGN KEY ("recorded_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" ADD CONSTRAINT "fk_exp_cons_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expedition_resource_consumed" ADD CONSTRAINT "fk_exp_consumed_expedition" FOREIGN KEY ("expedition_id") REFERENCES "expedition"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "fk_icr_destination_camp" FOREIGN KEY ("destination_camp_id") REFERENCES "camp"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "fk_icr_origin_camp" FOREIGN KEY ("origin_camp_id") REFERENCES "camp"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "fk_sic_creado_por" FOREIGN KEY ("created_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD CONSTRAINT "fk_sic_respondido_por" FOREIGN KEY ("responded_by") REFERENCES "system_user"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD CONSTRAINT "fk_movimiento_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD CONSTRAINT "fk_movimiento_registrado_por" FOREIGN KEY ("recorded_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD CONSTRAINT "fk_movimiento_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" ADD CONSTRAINT "fk_alert_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" ADD CONSTRAINT "fk_alerta_movimiento" FOREIGN KEY ("movement_id") REFERENCES "inventory_movement"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_alert" ADD CONSTRAINT "fk_alerta_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "fk_notificacion_usuario" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "fk_notification_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" ADD CONSTRAINT "fk_sol_rec_solicitud" FOREIGN KEY ("request_id") REFERENCES "intercamp_request"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" ADD CONSTRAINT "fk_sol_rec_tipo_recurso" FOREIGN KEY ("resource_type_id") REFERENCES "resource_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" ADD CONSTRAINT "fk_request_person_occupation" FOREIGN KEY ("occupation_id") REFERENCES "occupation"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" ADD CONSTRAINT "fk_request_person_person" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" ADD CONSTRAINT "fk_request_person_request" FOREIGN KEY ("request_id") REFERENCES "intercamp_request"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_status_history" ADD CONSTRAINT "fk_historial_cambiado_por" FOREIGN KEY ("changed_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_status_history" ADD CONSTRAINT "fk_person_history" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "fk_sesion_usuario" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "fk_session_camp" FOREIGN KEY ("camp_id") REFERENCES "camp"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transfer" ADD CONSTRAINT "fk_transfer_request" FOREIGN KEY ("request_id") REFERENCES "intercamp_request"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD CONSTRAINT "fk_transfer_history_transfer" FOREIGN KEY ("transfer_id") REFERENCES "transfer"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transfer_history" ADD CONSTRAINT "fk_transfer_history_user" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_role_history" ADD CONSTRAINT "fk_historial_rol_cambiado_por" FOREIGN KEY ("changed_by") REFERENCES "system_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_role_history" ADD CONSTRAINT "fk_historial_rol_usuario" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transfer_person" ADD CONSTRAINT "fk_transfer_person_person" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transfer_person" ADD CONSTRAINT "fk_transfer_person_transfer" FOREIGN KEY ("transfer_id") REFERENCES "transfer"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" ADD CONSTRAINT "FK_password_reset_token_user" FOREIGN KEY ("user_id") REFERENCES "system_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
